### ISSUE TITLE
Criando a curva da trajetória da bola.

### ISSUE THREAD

**Issue by wallace0003** [JnSGoncalves/Projeto-Ora-Bolas#1]
- [x] Deixar um arquivo separado para as funções.
- [x] Montando dimensões do campo e testando no gráfico
- [x] Estudar a biblioteca matplotlib
- [x] verificar a função da trajetória da bola em função do tempo
- [x] criar uma lista para os pontos em x e y
- [x] Percorrer todos os pontos da bola armazenando x e y na lista correspondentes.

**Comment by wallace0003** [comment]
Falta agora a implementação do menu que irei deixar para o final do projeto, pois acho que faz mais sentido. E, a Implementação do gráfico da trajetória da bola foi um sucesso!

**Comment by Jota-721** [comment]
Tentei dar uma olhada no código e não consegui rodar por aqui, estava dando alguns erros nos imports
